name: 'collisions_warehouse'
version: '1.0.0'
config-version: 2

profile: 'collisions_warehouse'

flags:
  partial_parse: true

model-paths: ["models"]
test-paths: ["tests"]
docs-paths: ["docs"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  collisions_warehouse:
    staging:
      +materialized: table
    marts:
      +materialized: table
      +schema: cdw